import { enforceHttpTransportPolicy } from "./src/lib/edge-http-policy";

// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// @ts-expect-error Generated only after the OpenNext build step.
import openNextWorker from "./.open-next/worker.js";

const worker = {
  fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    return enforceHttpTransportPolicy(request, (secureRequest) =>
      openNextWorker.fetch(secureRequest, env, ctx),
    );
  },
};

export default worker;

// Keep the generated Durable Object exports available if cache bindings are
// enabled in a future OpenNext configuration.
// @ts-expect-error Generated only after the OpenNext build step.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
